version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL_PROD=127.0.0.1:6066/api
        - VITE_LOCAL_DEV=true
    ports:
      - "6066:6066"
    env_file:
      - ./server/.env
    command: bash -c "service nginx start && python run.py --dev" 
