name: Deploy MindOfShaun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest,${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: type=registry,ref=123456789012.dkr.ecr.us-east-2.amazonaws.com/prod/paxxium:buildcache
          cache-to: type=registry,ref=123456789012.dkr.ecr.us-east-2.amazonaws.com/prod/paxxium:buildcache,mode=max

      # - name: Calculate deployment signature
      #   run: |
      #     echo "DEPLOY_SIGNATURE=$(echo -n '' | openssl dgst -sha256 -hmac '${{ secrets.DEPLOY_SECRET }}' | awk '{print $2}')" >> $GITHUB_ENV
          
      # - name: Trigger deployment
      #   run: |
      #     curl -X POST \
      #       -H "X-Deploy-Signature: ${{ env.DEPLOY_SIGNATURE }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{"image": "${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}"}' \
      #       https://api.paxxium.com/api/deploy/mindofshaun