name: Deploy MindOfShaun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate deployment signature
        run: |
          # Create a timestamp for uniqueness
          TIMESTAMP=$(date +%s)
          PAYLOAD='{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "timestamp": "'$TIMESTAMP'"}'
          echo "DEPLOY_SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac '${{ secrets.DEPLOY_SECRET }}' | awk '{print $2}')" >> $GITHUB_ENV
          echo "PAYLOAD=$PAYLOAD" >> $GITHUB_ENV
          
      - name: Trigger deployment
        run: |
          curl -X POST \
            -H "X-Deploy-Signature: ${{ env.DEPLOY_SIGNATURE }}" \
            -H "Content-Type: application/json" \
            -d '${{ env.PAYLOAD }}' \
            https://api.paxxium.com/api/deploy/mindofshaun